import { describe, it, expect } from 'vitest';
import { StreamingStft } from './streaming-stft';
import sineBin100 from './__fixtures__/oracle/sine-bin100-44k1-2048.json';
import sine440p7 from './__fixtures__/oracle/sine-440p7-44k1-2048.json';
import twotoneNoise from './__fixtures__/oracle/twotone-noise-44k1-2048.json';
import chirp from './__fixtures__/oracle/chirp-100-4k-44k1-2048.json';
import sineBin100At48k from './__fixtures__/oracle/sine-bin100-48k-2048.json';
import sine440p7At4096 from './__fixtures__/oracle/sine-440p7-44k1-4096.json';

/**
 * Independent-oracle verification: librosa-generated STFT magnitudes
 * (complex128 math, generated by scripts/generate_fixtures.py) vs the
 * production StreamingStft, on bit-identical float32 input samples
 * stored in each fixture.
 *
 * Tolerance is the cross-implementation tier from docs/TOLERANCES.md:
 * rtol 1e-4 (the float32 pipeline's accumulated-error budget) with
 * atol 1e-7 flooring the near-zero bins where relative error is
 * meaningless. Bin 0 is excluded — Coral applies the 2x one-sided
 * factor to DC where it shouldn't (documented wart in spectrogram.ts);
 * the fixtures store librosa's true DC value for the day that's fixed.
 *
 * If this test starts failing NEAR the tolerance rather than wildly,
 * do not loosen rtol — that reopens the float64-promotion decision in
 * TOLERANCES.md instead.
 */

interface OracleFixture {
  name: string;
  sampleRate: number;
  fftSize: number;
  hopSize: number;
  numBins: number;
  frames: number;
  librosaVersion: string;
  samples: number[];
  expectedMagnitudes: number[][];
}

const RTOL = 1e-4;
const ATOL = 1e-7;

const FIXTURES: OracleFixture[] = [
  sineBin100,
  sine440p7,
  twotoneNoise,
  chirp,
  sineBin100At48k,
  sine440p7At4096,
];

describe('librosa oracle fixtures (streaming STFT)', () => {
  // Batch path coverage transfers via stft-parity.test.ts (bit-identical).
  for (const fx of FIXTURES) {
    it(`matches librosa ${fx.librosaVersion} on ${fx.name}`, () => {
      const stft = new StreamingStft(fx.fftSize, fx.hopSize);
      const frames = stft.pushSamples(new Float32Array(fx.samples));
      expect(frames.length).toBe(fx.frames);

      // Measured worst cases, split by which tolerance term governs:
      // rel error only meaningfully constrains bins with |exp| above
      // ATOL/RTOL (= 1e-3); below that the atol floor dominates and rel
      // error is noise about noise. Both margins are reported so the
      // real headroom against the tier is visible, not just pass/fail.
      const SIGNIFICANT = ATOL / RTOL;
      let maxRel = 0;
      let maxRelAt = '';
      let maxAbsSmall = 0;

      for (let f = 0; f < fx.frames; f++) {
        const got = frames[f]!;
        const exp = fx.expectedMagnitudes[f]!;
        expect(got.length).toBe(fx.numBins);
        for (let b = 1; b < fx.numBins; b++) {
          // b starts at 1: bin 0 (DC) excluded, see header.
          const e = exp[b] as number;
          const g = got[b] as number;
          const err = Math.abs(g - e);
          if (err > ATOL + RTOL * Math.abs(e)) {
            expect.fail(
              `${fx.name} frame ${f} bin ${b}: got ${g}, librosa ${e}, ` +
                `|diff| ${err} > ${ATOL} + ${RTOL}·|exp|`
            );
          }
          if (Math.abs(e) > SIGNIFICANT) {
            const rel = err / Math.abs(e);
            if (rel > maxRel) {
              maxRel = rel;
              maxRelAt = `frame ${f} bin ${b}`;
            }
          } else if (err > maxAbsSmall) {
            maxAbsSmall = err;
          }
        }
      }

      // Lifecycle-level report (once per fixture, not per frame).
      console.log(
        `[oracle] ${fx.name}: max rel ${maxRel.toExponential(2)} at ${maxRelAt} ` +
          `(rtol ${RTOL}); small-bin max abs ${maxAbsSmall.toExponential(2)} (atol ${ATOL})`
      );
    });
  }
});
